[DEFAULT]
illyes_var = 10
sep = "-"
replace_sep_with = "."

[Layouts]
y_value_default = "cost_cumulative"
axis_lock = false
collapse_open = false

[Scaling]
p_effective = 100

[Main]
file_name_default = "Asset Model - Pole - Timber.xlsx"
file_units_default = "years"
model_units_default = "months"
input_units_default = "years"

[PofBase]
on_error_use_default = true
handle_invalid_data = true
handle_update_error = true
use_default = false

[Component]
allow_system_impact = true
indicator_input_fields = ["perfect", "initial", "failed"] 
forecast_confidence_interval = 0.8

[FailureMode]
remain_failed = true

name = "fm"
active = true
pf_curve = "step"
pf_interval = 0
pf_std = 0


[Indicator]
PERFECT = 100
FAILED = 0

[Task]


[Distribution]
name = "dist"
alpha = 50
beta = 1
gamma = 10

[AssetModelLoader]

[FleetDataLoader]

[PoleFleetDataLoader]

[Consequence]